
% This is a sample main file that reads two grayordinate fmri files generated by bfp and outputs the synced files.

clc;clear all;close all;
addpath(genpath('/big_disk/ajoshi/coding_ground/bfp/'));


a=dir('/big_disk/ajoshi/sample_from_andrew');
rho_beforeLR1=0;rho_beforeLR2=0;
rho_afterL=0;rho_afterR=0;
nsub=0;
for jj=1:length(a)
    
    if isnan(str2double(a(jj).name(1)))
        continue;
    end
    
    g1=ft_read_cifti(sprintf('/big_disk/ajoshi/sample_from_andrew/%s/rfMRI_1_LR/rfMRI_1_LR_LNLM_p72.dtseries.nii',a(jj).name));
    g2=ft_read_cifti(sprintf('/big_disk/ajoshi/sample_from_andrew/%s/rfMRI_2_LR/rfMRI_2_LR_LNLM_p72.dtseries.nii',a(jj).name));
        
    indL1=g1.brainstructure==1;
    indL2=g2.brainstructure==1;
    indR1=g1.brainstructure==2;
    indR2=g2.brainstructure==2;
    
    datL1=normalizeData(g1.dtseries(indL1,:)');
    datL2=normalizeData(g2.dtseries(indL2,:)');
    datR1=normalizeData(g1.dtseries(indR1,:)');
    datR2=normalizeData(g2.dtseries(indR2,:)');
    
    %g1.dtseries=g1.dtseries(1:32000,:);
    %g2.dtseries=g2.dtseries(1:32000,:);
    
    rho_beforeLR1=rho_beforeLR1+sum(datL1.*datR1,1);
    rho_beforeLR2=rho_beforeLR2+sum(datL2.*datR2,1);
    
    [dtseries_sync,R]=brainSync(datL1,datL2);
    rho_afterL=rho_afterL+sum(datL1.*dtseries_sync,1);
    rho_afterR=rho_afterR+sum(datR1.*(R*datR2),1);
    nsub=nsub+1;    
    fprintf('Correlation before=%g, after=%g,%g\n',mean(rho_beforeLR1)/nsub, mean(rho_afterL)/nsub, mean(rho_afterR)/nsub); 
    nsub
end

addpath(genpath('/big_disk/ajoshi/coding_ground/svreg/src'))
clear sL sR
cm=jet(100);cm(1,:)=.5;
sL1=gifti('/big_disk/ajoshi/sample_from_andrew/common_anat/100307.L.midthickness.11k_fs_LR.surf.gii');
sR1=gifti('/big_disk/ajoshi/sample_from_andrew/common_anat/100307.R.midthickness.11k_fs_LR.surf.gii');
sL.faces=double(sL1.faces);sR.faces=double(sR1.faces);sL.vertices=double(sL1.vertices);sR.vertices=double(sR1.vertices);
sL=smooth_cortex_fast(sL,.1,300);
a=figure;
patch('vertices',sL.vertices,'faces',double(sL.faces),'facevertexcdata',(rho_afterL/nsub)','edgecolor','none','facecolor','interp');
axis equal;axis off;view(-90,10);camlight;material dull;colormap(cm);caxis([0,1]);
saveas(a,'left_corr1.png');
view(90,-10);camlight;saveas(a,'left_corr2.png');

sR=smooth_cortex_fast(sR,.1,300);
a=figure;
patch('vertices',sR.vertices,'faces',double(sR.faces),'facevertexcdata',(rho_afterR/nsub)','edgecolor','none','facecolor','interp');
axis equal;axis off;view(-90,-10);camlight;material dull;colormap(cm);caxis([0,1]);
saveas(a,'right_corr1.png');
view(90,10);camlight;saveas(a,'right_corr2.png');

a=figure;
patch('vertices',sR.vertices,'faces',double(sR.faces),'facevertexcdata',(rho_beforeLR1/nsub)','edgecolor','none','facecolor','interp');
axis equal;axis off;view(-90,-10);camlight;material dull;colormap(cm);caxis([0,1]);
saveas(a,'right_LRcorr1.png');
view(90,10);camlight;saveas(a,'right_LRcorr2.png');

